:toc: macro
:toc-title:
:toclevels: 99

# Orion

A minimal, rails'esk routing library for `HTTP::Server`.

Orion allows you to easily add routes, groups, and middleware in order to
construct your application's routing layer.

toc::[]

## Purpose

The purpose of the Orion router is to connect URLs to code. It provides a flexible
and comprehensive DSL that will allow you to cover a variety of use cases. In addition,
Orion will also generate a series of helpers to easily reference the defined paths
within your application.

## Installation

Add this to your application's `shard.yml`:

```yaml
dependencies:
  orion:
    github: obsidian/orion
```

... and require Orion in your project.

```crystal
require "orion"
```

## Usage

### Defining a router

You must define a class that inherits from `Orion::Router`. You will define your
routes directly in this class.

```crystal
class MyApplicationRouter < Orion::Router
  # ...
end
```

[[generic-route-arguments]]
### Generic route arguments
There are a variety of ways that you can interact with basic routes. Below are
some examples and guidelines on the different ways you can interact with the router.

#### Using `to: String` to target a controller and action
One of the most common ways we will be creating routes in this guide is to use
the `to` argument supplied with a controller and action in the form of a string.
In the example below `Users#create` will map to `UsersController.new(cxt : HTTP::Server::Context).create`.

```crystal
class MyApplicationRouter < Orion::Router
  post "users", to: "Users#create"
end
```

#### Using `controller: Type` and `action: Method`
A longer form of the `to` argument strategy above allows us to pass the controller and action
independently.

```crystal
class MyApplicationRouter < Orion::Router
  post "users", controller: UsersController, action: create
end
```

#### Using `controller: Type`
Alternatively we can also drop the action and the http verb will be used.
`post "/users", controller: Users` would map to `UsersController.new(cxt : HTTP::Server::Context).post`.

```crystal
class MyApplicationRouter < Orion::Router
  post "users", controller: UsersController
end
```

#### Using a `call` able object
Sometimes, we may want a more link:https://github.com/kemalcr/kemal[kemal] or
link:http://sinatrarb.com/[sinatra] like approach. A second argument can be any
object that responds to `#call(cxt : HTTP::Server::Context)`.

```crystal
class MyApplicationRouter < Orion::Router
  post "users", ->(cxt : HTTP::Server::Context) {
    cxt.response.puts "foo"
  }
end
```

### Basic Routing

#### Base route using `root`

Lets define the routers's `root` route. `root` is simply an alias for `get '/', action`.
All routes can either be a `String` pointing to a Controller action or a `Proc`
accepting `HTTP::Server::Context` as a single argument. If a `String` is used like `controller#action`, it will expand into `Controller.new(context : HTTP::Server::Context).action`, therefor A controller must
have an initializer that takes `HTTP::Server::Context` as an argument, and the
specified action must not contain arguments.

```crystal
  class MyApplicationRouter < Orion::Router
    root to: "home#index"
  end
```

#### HTTP verb based routes

A common way to interact with the router is to use standard HTTP verbs. Orion
supports all the standard HTTP verbs:

`get`, `head`, `post`, `put`, `delete`, `connect`, `options`, `trace`, and `patch`

You can simply use one of the methods within the router and pass it's router and
any variation of the xref:generic-route-arguments[Generic Route Arguments].

```crystal
class MyApplicationRouter < Orion::Router
  post "users", to: "users#create"
end
```

#### Catch all routes using `match`

In some instances you may just want to redirect all verbs to a particular
controller and action.

You can simply use the `match` method within the router and pass it's router and
any variation of the xref:generic-route-arguments[Generic Route Arguments].

```crystal
class MyApplicationRouter < Orion::Router
  match "404", controller: ErrorsController, action: error_404
end
```

### Resource Based Routing

*TODO*

#### Collections of resources

*TODO*

#### Singular Resources

*TODO*

#### Additional Options

*TODO*

### Scopes & Nested Routes

*TODO*

#### Clearing Handlers

*TODO*

#### Helper prefixes

*TODO*

### Concerns – Reusable code in your routers

*TODO*

#### Defining a concern

*TODO*

#### Using concerns

*TODO*

### Constraints - More advanced rules for your routes

*TODO*

#### Parameter constraints

*TODO*

#### Format constraints

*TODO*

#### Domain & Subdomain constraints

*TODO*

#### Custom Constraints

*TODO*

### Instrumenting handlers _(a.k.a. middleware)_

*TODO*

### Helpers

*TODO*

#### Making helpers from your routes

*TODO*

#### Using helpers in your code

*TODO*

[quote]
*NOTE:*
You can omit the action to map all remaining HTTP verbs to their respective
controller actions.

```crystal
class MyApplicationRouter < Orion::Router
  match "users", controller: UsersController
end
```

## Benchmarks

Benchmarks can be run with `./benchmark`.

## Contributing

1. Fork it https://github.com/<your-github-name>/orion/fork
2. Create your feature branch (git checkout -b my-new-feature)
3. Commit your changes (git commit -am 'Add some feature')
4. Push to the branch (git push origin my-new-feature)
5. Create a new Pull Request

## Contributors

- link:https://github.com/jwaldrip[Jason Waldrip (jwaldrip)] - creator, maintainer
