version: "3"
services:
  benchmark:
    build:
      context: ./benchmark
    links:
      - kemal
      - orion
      - sinatra
    volumes:
      - ./results.txt:/tmp/results.txt
    environment:
      TEST_ROUTE: /applications/123/tokens/123
    command:
      - wrkall kemal orion sinatra
  kemal:
    build:
      context: ./kemal
    environment:
      PORT: 3000
  orion:
    build:
      context: ./orion
    environment:
      PORT: 3000
  sinatra:
    build:
      context: ./sinatra
    environment:
      PORT: 3000
