version: '3'
services:
  benchmark-base: &benchmark
    build:
      context: ./benchmark
    volumes:
      - ./:/hostmachine
    environment:
      OUT_FILE: /hostmachine/results.txt
      PORT: 3000
      TEST_ROUTE: /applications/123/tokens/123
    command: benchmark kemal
  benchmark-kemal:
    <<: *benchmark
    links:
      - kemal
    command: benchmark kemal
  kemal:
    build:
      context: ./kemal
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-orion:
    <<: *benchmark
    links:
      - orion
    command: benchmark orion
  orion:
    build:
      context: ./orion
    environment:
      PORT: 3000
    expose:
      - 3000
  benchmark-sinatra:
    <<: *benchmark
    links:
      - sinatra
    command: benchmark sinatra
  sinatra:
    build:
      context: ./sinatra
    environment:
      PORT: 3000
    expose:
      - 3000
